# Module 3
#   Programming Assignment 4
#     Prob-5.py

# Edward LaManna


def main():
     try:
        eval(2)
        print("x:", x)
    except TypeError:
        exit
    except:
        print("exiting")
        exit

main()
